// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.12.4
// source: proto/user/proto/user.proto

package golang

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Genders int32

const (
	Genders_MALE   Genders = 0
	Genders_FEMALE Genders = 1
)

// Enum value maps for Genders.
var (
	Genders_name = map[int32]string{
		0: "MALE",
		1: "FEMALE",
	}
	Genders_value = map[string]int32{
		"MALE":   0,
		"FEMALE": 1,
	}
)

func (x Genders) Enum() *Genders {
	p := new(Genders)
	*p = x
	return p
}

func (x Genders) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Genders) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_user_proto_user_proto_enumTypes[0].Descriptor()
}

func (Genders) Type() protoreflect.EnumType {
	return &file_proto_user_proto_user_proto_enumTypes[0]
}

func (x Genders) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Genders.Descriptor instead.
func (Genders) EnumDescriptor() ([]byte, []int) {
	return file_proto_user_proto_user_proto_rawDescGZIP(), []int{0}
}

type EducationLevels int32

const (
	EducationLevels_STUDENT   EducationLevels = 0
	EducationLevels_BACHELOR  EducationLevels = 1
	EducationLevels_MASTER    EducationLevels = 2
	EducationLevels_DOCTORATE EducationLevels = 3
	EducationLevels_OTHER     EducationLevels = 4
)

// Enum value maps for EducationLevels.
var (
	EducationLevels_name = map[int32]string{
		0: "STUDENT",
		1: "BACHELOR",
		2: "MASTER",
		3: "DOCTORATE",
		4: "OTHER",
	}
	EducationLevels_value = map[string]int32{
		"STUDENT":   0,
		"BACHELOR":  1,
		"MASTER":    2,
		"DOCTORATE": 3,
		"OTHER":     4,
	}
)

func (x EducationLevels) Enum() *EducationLevels {
	p := new(EducationLevels)
	*p = x
	return p
}

func (x EducationLevels) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EducationLevels) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_user_proto_user_proto_enumTypes[1].Descriptor()
}

func (EducationLevels) Type() protoreflect.EnumType {
	return &file_proto_user_proto_user_proto_enumTypes[1]
}

func (x EducationLevels) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EducationLevels.Descriptor instead.
func (EducationLevels) EnumDescriptor() ([]byte, []int) {
	return file_proto_user_proto_user_proto_rawDescGZIP(), []int{1}
}

type MaritalStatuses int32

const (
	MaritalStatuses_MARRIED MaritalStatuses = 0
	MaritalStatuses_SINGLE  MaritalStatuses = 1
)

// Enum value maps for MaritalStatuses.
var (
	MaritalStatuses_name = map[int32]string{
		0: "MARRIED",
		1: "SINGLE",
	}
	MaritalStatuses_value = map[string]int32{
		"MARRIED": 0,
		"SINGLE":  1,
	}
)

func (x MaritalStatuses) Enum() *MaritalStatuses {
	p := new(MaritalStatuses)
	*p = x
	return p
}

func (x MaritalStatuses) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MaritalStatuses) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_user_proto_user_proto_enumTypes[2].Descriptor()
}

func (MaritalStatuses) Type() protoreflect.EnumType {
	return &file_proto_user_proto_user_proto_enumTypes[2]
}

func (x MaritalStatuses) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MaritalStatuses.Descriptor instead.
func (MaritalStatuses) EnumDescriptor() ([]byte, []int) {
	return file_proto_user_proto_user_proto_rawDescGZIP(), []int{2}
}

type EmptyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_proto_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_user_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone      string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password   string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	TelegramId string `protobuf:"bytes,3,opt,name=telegramId,proto3" json:"telegramId,omitempty"`
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_proto_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetTelegramId() string {
	if x != nil {
		return x.TelegramId
	}
	return ""
}

type TelegramLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TelegramId string `protobuf:"bytes,1,opt,name=telegramId,proto3" json:"telegramId,omitempty"`
}

func (x *TelegramLoginRequest) Reset() {
	*x = TelegramLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_proto_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TelegramLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramLoginRequest) ProtoMessage() {}

func (x *TelegramLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramLoginRequest.ProtoReflect.Descriptor instead.
func (*TelegramLoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *TelegramLoginRequest) GetTelegramId() string {
	if x != nil {
		return x.TelegramId
	}
	return ""
}

type CreatorLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *CreatorLoginResponse) Reset() {
	*x = CreatorLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_proto_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatorLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatorLoginResponse) ProtoMessage() {}

func (x *CreatorLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatorLoginResponse.ProtoReflect.Descriptor instead.
func (*CreatorLoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *CreatorLoginResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreatorLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VoterLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *VoterLoginResponse) Reset() {
	*x = VoterLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_proto_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoterLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoterLoginResponse) ProtoMessage() {}

func (x *VoterLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoterLoginResponse.ProtoReflect.Descriptor instead.
func (*VoterLoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *VoterLoginResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VoterLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *UserIdRequest) Reset() {
	*x = UserIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_proto_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdRequest) ProtoMessage() {}

func (x *UserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdRequest.ProtoReflect.Descriptor instead.
func (*UserIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Preferences map[string]string `protobuf:"bytes,2,rep,name=preferences,proto3" json:"preferences,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_proto_user_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_user_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserInfo) GetPreferences() map[string]string {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type UpdateVoterProfileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	City           *string          `protobuf:"bytes,1,opt,name=city,proto3,oneof" json:"city,omitempty"`
	Gender         *Genders         `protobuf:"varint,2,opt,name=gender,proto3,enum=user.Genders,oneof" json:"gender,omitempty"`
	Age            *int32           `protobuf:"varint,3,opt,name=age,proto3,oneof" json:"age,omitempty"`
	Job            *string          `protobuf:"bytes,4,opt,name=job,proto3,oneof" json:"job,omitempty"`
	EducationLevel *EducationLevels `protobuf:"varint,5,opt,name=educationLevel,proto3,enum=user.EducationLevels,oneof" json:"educationLevel,omitempty"`
	FieldOfStudy   *string          `protobuf:"bytes,6,opt,name=fieldOfStudy,proto3,oneof" json:"fieldOfStudy,omitempty"`
	MaritalStatus  *MaritalStatuses `protobuf:"varint,7,opt,name=maritalStatus,proto3,enum=user.MaritalStatuses,oneof" json:"maritalStatus,omitempty"`
}

func (x *UpdateVoterProfileRequest) Reset() {
	*x = UpdateVoterProfileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_proto_user_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVoterProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVoterProfileRequest) ProtoMessage() {}

func (x *UpdateVoterProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_user_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVoterProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateVoterProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_user_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateVoterProfileRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *UpdateVoterProfileRequest) GetGender() Genders {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return Genders_MALE
}

func (x *UpdateVoterProfileRequest) GetAge() int32 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

func (x *UpdateVoterProfileRequest) GetJob() string {
	if x != nil && x.Job != nil {
		return *x.Job
	}
	return ""
}

func (x *UpdateVoterProfileRequest) GetEducationLevel() EducationLevels {
	if x != nil && x.EducationLevel != nil {
		return *x.EducationLevel
	}
	return EducationLevels_STUDENT
}

func (x *UpdateVoterProfileRequest) GetFieldOfStudy() string {
	if x != nil && x.FieldOfStudy != nil {
		return *x.FieldOfStudy
	}
	return ""
}

func (x *UpdateVoterProfileRequest) GetMaritalStatus() MaritalStatuses {
	if x != nil && x.MaritalStatus != nil {
		return *x.MaritalStatus
	}
	return MaritalStatuses_MARRIED
}

var File_proto_user_proto_user_proto protoreflect.FileDescriptor

var file_proto_user_proto_user_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x22, 0x0f, 0x0a, 0x0d, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x63, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6c,
	0x65, 0x67, 0x72, 0x61, 0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74,
	0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x14, 0x54, 0x65, 0x6c,
	0x65, 0x67, 0x72, 0x61, 0x6d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x49,
	0x64, 0x22, 0x3c, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x3a, 0x0a, 0x12, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x27, 0x0a, 0x0d, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x9d, 0x01, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x41, 0x0a, 0x0b, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x73, 0x1a, 0x3e, 0x0a, 0x10, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x97, 0x03, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56,
	0x6f, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x88, 0x01, 0x01, 0x12, 0x2a, 0x0a, 0x06, 0x67,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x48, 0x01, 0x52, 0x06, 0x67, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x15, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x48, 0x02, 0x52, 0x03, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x15,
	0x0a, 0x03, 0x6a, 0x6f, 0x62, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x03, 0x6a,
	0x6f, 0x62, 0x88, 0x01, 0x01, 0x12, 0x42, 0x0a, 0x0e, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x45, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x73, 0x48, 0x04, 0x52, 0x0e, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x27, 0x0a, 0x0c, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x4f, 0x66, 0x53, 0x74, 0x75, 0x64, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x05, 0x52, 0x0c, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x66, 0x53, 0x74, 0x75, 0x64, 0x79, 0x88,
	0x01, 0x01, 0x12, 0x40, 0x0a, 0x0d, 0x6d, 0x61, 0x72, 0x69, 0x74, 0x61, 0x6c, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x4d, 0x61, 0x72, 0x69, 0x74, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73,
	0x48, 0x06, 0x52, 0x0d, 0x6d, 0x61, 0x72, 0x69, 0x74, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x63, 0x69, 0x74, 0x79, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x61, 0x67, 0x65,
	0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6a, 0x6f, 0x62, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x65, 0x64, 0x75,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x42, 0x0f, 0x0a, 0x0d, 0x5f,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x66, 0x53, 0x74, 0x75, 0x64, 0x79, 0x42, 0x10, 0x0a, 0x0e,
	0x5f, 0x6d, 0x61, 0x72, 0x69, 0x74, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x1f,
	0x0a, 0x07, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x41, 0x4c,
	0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x45, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x01, 0x2a,
	0x52, 0x0a, 0x0f, 0x45, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x55, 0x44, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x12,
	0x0c, 0x0a, 0x08, 0x42, 0x41, 0x43, 0x48, 0x45, 0x4c, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x4d, 0x41, 0x53, 0x54, 0x45, 0x52, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x4f, 0x43,
	0x54, 0x4f, 0x52, 0x41, 0x54, 0x45, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x54, 0x48, 0x45,
	0x52, 0x10, 0x04, 0x2a, 0x2a, 0x0a, 0x0f, 0x4d, 0x61, 0x72, 0x69, 0x74, 0x61, 0x6c, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x41, 0x52, 0x52, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x49, 0x4e, 0x47, 0x4c, 0x45, 0x10, 0x01, 0x32,
	0xd8, 0x01, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3d, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x15,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x6f, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3a, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x15, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a,
	0x11, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72,
	0x61, 0x6d, 0x12, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72,
	0x61, 0x6d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xd0, 0x01, 0x0a, 0x0c, 0x56,
	0x6f, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x11, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d,
	0x12, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a,
	0x07, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x13, 0x5a,
	0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x6c, 0x61,
	0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_user_proto_user_proto_rawDescOnce sync.Once
	file_proto_user_proto_user_proto_rawDescData = file_proto_user_proto_user_proto_rawDesc
)

func file_proto_user_proto_user_proto_rawDescGZIP() []byte {
	file_proto_user_proto_user_proto_rawDescOnce.Do(func() {
		file_proto_user_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_user_proto_user_proto_rawDescData)
	})
	return file_proto_user_proto_user_proto_rawDescData
}

var file_proto_user_proto_user_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_user_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_user_proto_user_proto_goTypes = []interface{}{
	(Genders)(0),                      // 0: user.Genders
	(EducationLevels)(0),              // 1: user.EducationLevels
	(MaritalStatuses)(0),              // 2: user.MaritalStatuses
	(*EmptyResponse)(nil),             // 3: user.EmptyResponse
	(*RegisterRequest)(nil),           // 4: user.RegisterRequest
	(*TelegramLoginRequest)(nil),      // 5: user.TelegramLoginRequest
	(*CreatorLoginResponse)(nil),      // 6: user.CreatorLoginResponse
	(*VoterLoginResponse)(nil),        // 7: user.VoterLoginResponse
	(*UserIdRequest)(nil),             // 8: user.UserIdRequest
	(*UserInfo)(nil),                  // 9: user.UserInfo
	(*UpdateVoterProfileRequest)(nil), // 10: user.UpdateVoterProfileRequest
	nil,                               // 11: user.UserInfo.PreferencesEntry
}
var file_proto_user_proto_user_proto_depIdxs = []int32{
	11, // 0: user.UserInfo.preferences:type_name -> user.UserInfo.PreferencesEntry
	0,  // 1: user.UpdateVoterProfileRequest.gender:type_name -> user.Genders
	1,  // 2: user.UpdateVoterProfileRequest.educationLevel:type_name -> user.EducationLevels
	2,  // 3: user.UpdateVoterProfileRequest.maritalStatus:type_name -> user.MaritalStatuses
	4,  // 4: user.CreatorService.Register:input_type -> user.RegisterRequest
	4,  // 5: user.CreatorService.Login:input_type -> user.RegisterRequest
	5,  // 6: user.CreatorService.LoginWithTelegram:input_type -> user.TelegramLoginRequest
	5,  // 7: user.VoterService.LoginWithTelegram:input_type -> user.TelegramLoginRequest
	10, // 8: user.VoterService.UpdateProfile:input_type -> user.UpdateVoterProfileRequest
	8,  // 9: user.VoterService.GetById:input_type -> user.UserIdRequest
	6,  // 10: user.CreatorService.Register:output_type -> user.CreatorLoginResponse
	6,  // 11: user.CreatorService.Login:output_type -> user.CreatorLoginResponse
	6,  // 12: user.CreatorService.LoginWithTelegram:output_type -> user.CreatorLoginResponse
	7,  // 13: user.VoterService.LoginWithTelegram:output_type -> user.VoterLoginResponse
	3,  // 14: user.VoterService.UpdateProfile:output_type -> user.EmptyResponse
	9,  // 15: user.VoterService.GetById:output_type -> user.UserInfo
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_user_proto_user_proto_init() }
func file_proto_user_proto_user_proto_init() {
	if File_proto_user_proto_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_user_proto_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_proto_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_proto_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TelegramLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_proto_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatorLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_proto_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoterLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_proto_user_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_proto_user_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_proto_user_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVoterProfileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_user_proto_user_proto_msgTypes[7].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_user_proto_user_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_user_proto_user_proto_goTypes,
		DependencyIndexes: file_proto_user_proto_user_proto_depIdxs,
		EnumInfos:         file_proto_user_proto_user_proto_enumTypes,
		MessageInfos:      file_proto_user_proto_user_proto_msgTypes,
	}.Build()
	File_proto_user_proto_user_proto = out.File
	file_proto_user_proto_user_proto_rawDesc = nil
	file_proto_user_proto_user_proto_goTypes = nil
	file_proto_user_proto_user_proto_depIdxs = nil
}
