services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: fateme
      MONGO_INITDB_ROOT_PASSWORD: fateme
    networks:
      - app_network
networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local