# .golangci.yml
version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gofmt
    - revive
    - gosimple
    - unused
    - ineffassign
    - gosec
    - gocyclo