services:
  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: fateme
      MONGO_INITDB_ROOT_PASSWORD: fateme
    networks:
      - app_network

  user-management-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://fateme:fateme@mongodb:27017/users?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app_network
networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
