services:
  mongodb:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - app_network
      - monitoring_net

  poll-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7071:7071"
      - "9091:9091"
    environment:
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
    depends_on:
      - mongodb
    networks:
      - app_network
      - monitoring_net

networks:
  app_network:
    driver: bridge
  monitoring_net:
    external: true

volumes:
  mongo_data:
    driver: local
