name: Service CI Template

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      service-path:
        required: true
        type: string

jobs:
  test:
    name: ${{ inputs.service-name }} - Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Tests
        run: cd ${{ inputs.service-path }} && ./gradlew test --stacktrace

  quality:
    name: ${{ inputs.service-name }} - Code Quality
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Detekt
        run: cd ${{ inputs.service-path }} && ./gradlew detekt --stacktrace

  mutation-test:
    name: Mutation Testing (Pitest)
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Mutation Tests
        run: cd  ${{ inputs.service-path }} && ./gradlew pitest

      - name: Upload Pitest Report
        uses: actions/upload-artifact@v4
        with:
          name: pitest-report
          path:  ${{ inputs.service-path }}/build/reports/pitest

  build:
    name: ${{ inputs.service-name }} - Build
    runs-on: ubuntu-latest
    needs: [test, quality]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build
        run: cd ${{ inputs.service-path }} && ./gradlew build --stacktrace
