name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Unit Tests
        run: cd userManagement && ./gradlew test --stacktrace

  quality:
    name: Code Quality (Detekt)
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Detekt
        run: cd userManagement && ./gradlew detekt --stacktrace

      - name: Upload Detekt Report
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          path: userManagement/build/reports/detekt


  mutation-test:
    name: Mutation Testing (Pitest)
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Mutation Tests
        run: cd userManagement && ./gradlew pitest

      - name: Upload Pitest Report
        uses: actions/upload-artifact@v4
        with:
          name: pitest-report
          path: userManagement/build/reports/pitest

  build:
    name: Build App
    runs-on: ubuntu-latest
    needs: [test, quality]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: cd userManagement && ./gradlew build --stacktrace
