name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          java-package: jdk
          architecture: x64
          distribution: 'adoptopenjdk'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Run tests
        run: ./gradlew test
