name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          architecture: x64

      - name: Build with Gradle
        run: cd userManagement && ./gradlew build --stacktrace

      - name: Run Detekt
        run: cd userManagement && ./gradlew detekt

      - name: Run Unit Tests
        run: cd userManagement && ./gradlew test